# Header
menu:
  目录: /archives
  iOS开发: /categories/iOS开发
  二三事: /categories/二三事
  标签云: /tags/
  关于: /about/

# SubNav
subnav:
  github: "https://github.com/yimouleng"
  weibo: "http://weibo.com/yimouleng"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  QQ: "http://shang.qq.com/wpa/qunwpa?idkey=ac73346414b7bc620d16a1553318221a96d0fb90832d39995c539098731e21b6"
  mail: "mailto:yimouleng@gamil.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /resources/avatar.jpg

#你的头像url
avatar: /resources/avatar.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: yimouleng
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  我的博客: http://yimouleng.com/


#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 静水流深，沧笙踏歌；三生阴晴圆缺，一朝悲欢离合。即便世界与我为敌，只要心还透明，就能折射希望。

#是否显示边栏中的搜索框 
#search_box: true